include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - iljali-app/**
    - lib/core/map/web/naver_map_web_layer_web.dart
    - lib/core/address/web/daum_postcode_web_layer_web.dart
    - lib/core/config/naver_map_web_client_id_loader_web.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
