server {
    listen 443 ssl;
    http2 on;
    server_name www.iljari.app iljari.app app.iljari.app;

    ssl_certificate     /etc/letsencrypt/live/iljari.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/iljari.app/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 25m;
    include /etc/nginx/snippets/web-variants.conf;
}
